import type { Category, DishWithCategory, Table as TableType } from './database.types';

const dishImages: Record<string, string> = {
  'shashlyk-svynya': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80',
  'shashlyk-yalovychyna': 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&q=80',
  'shashlyk-kurka': 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&q=80',
  'shashlyk-barannya': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
  'steak-ribeye': 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=600&q=80',
  'steak-filet-mignon': 'https://images.unsplash.com/photo-1603048297172-925c627c9cfb?w=600&q=80',
  'salad-caesar': 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=600&q=80',
  'salad-greek': 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=80',
  'borsch': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80',
  'solyanka': 'https://images.unsplash.com/photo-1604762524885-3b3f7e0c6d8a?w=600&q=80',
  'potato-village': 'https://images.unsplash.com/photo-1592415497089-6c3cf76b3d2e?w=600&q=80',
  'vegetables-grill': 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
  'lemonade': 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80',
  'tea-thyme': 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&q=80',
  'napoleon-cake': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80',
  'honey-cake': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80',
};

function img(slug: string): string {
  return dishImages[slug] || '';
}

export const fallbackCategories: Category[] = [
  {
    id: 'shashliks',
    name: 'Шашлики',
    slug: 'shashliks',
    description: 'Найсмачніші шашлики на живому вогні',
    image_url: null,
    display_order: 1,
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'steaks',
    name: 'Стейки',
    slug: 'steaks',
    description: 'Соковиті стейки преміум класу',
    image_url: null,
    display_order: 2,
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'salads',
    name: 'Салати',
    slug: 'salads',
    description: 'Свіжі салати з натуральних інгредієнтів',
    image_url: null,
    display_order: 3,
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'soups',
    name: 'Перші страви',
    slug: 'soups',
    description: 'Наваристі супи за домашніми рецептами',
    image_url: null,
    display_order: 4,
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'garnirs',
    name: 'Гарніри',
    slug: 'garnirs',
    description: 'Апетитні гарніри до будь-якої страви',
    image_url: null,
    display_order: 5,
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'drinks',
    name: 'Напої',
    slug: 'drinks',
    description: 'Освіжаючі та гарячі напої',
    image_url: null,
    display_order: 6,
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'deserts',
    name: 'Десерти',
    slug: 'deserts',
    description: 'Солодкі десерти на будь-який смак',
    image_url: null,
    display_order: 7,
    is_active: true,
    created_at: '',
    updated_at: '',
  },
];

const catBySlug: Record<string, Category> = {};
for (const cat of fallbackCategories) {
  catBySlug[cat.slug] = cat;
}

export const fallbackDishes: DishWithCategory[] = [
  {
    id: 'shashlyk-svynya',
    category_id: 'shashliks',
    name: 'Шашлик зі свинини',
    slug: 'shashlyk-svynya',
    description: 'Класичний шашлик з шийної частини',
    ingredients: ['свинина', 'цибуля', 'спеції', 'сало'],
    price: 280,
    weight_grams: 300,
    image_url: img('shashlyk-svynya'),
    is_popular: true,
    is_available: true,
    display_order: 1,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'shashlyk-yalovychyna',
    category_id: 'shashliks',
    name: 'Шашлик з яловичини',
    slug: 'shashlyk-yalovychyna',
    description: 'Ніжний шашлик з мраморової яловичини',
    ingredients: ['яловичина', 'цибуля', 'спеції'],
    price: 320,
    weight_grams: 300,
    image_url: img('shashlyk-yalovychyna'),
    is_popular: true,
    is_available: true,
    display_order: 2,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'shashlyk-kurka',
    category_id: 'shashliks',
    name: 'Шашлик з курки',
    slug: 'shashlyk-kurka',
    description: 'Соковитий шашлик з курячого стегна',
    ingredients: ['курка', 'цибуля', 'спеції', 'лимон'],
    price: 220,
    weight_grams: 300,
    image_url: img('shashlyk-kurka'),
    is_popular: false,
    is_available: true,
    display_order: 3,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'shashlyk-barannya',
    category_id: 'shashliks',
    name: 'Шашлик з баранини',
    slug: 'shashlyk-barannya',
    description: 'Ароматний шашлик з молодої баранини',
    ingredients: ['баранина', 'цибуля', 'спеції', 'кінза'],
    price: 380,
    weight_grams: 350,
    image_url: img('shashlyk-barannya'),
    is_popular: true,
    is_available: true,
    display_order: 4,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'lyulya-kebab',
    category_id: 'shashliks',
    name: 'Шашлик Люля-кебаб',
    slug: 'lyulya-kebab',
    description: 'Соковитий люля-кебаб з баранини на вугіллі',
    ingredients: ['баранина', 'цибуля', 'зелень', 'спеції'],
    price: 290,
    weight_grams: 250,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 5,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'shashlyk-assorti',
    category_id: 'shashliks',
    name: 'Шашлик асорті',
    slug: 'shashlyk-assorti',
    description: "Асорті з трьох видів м'яса на одному шампурі",
    ingredients: ['свинина', 'яловичина', 'курка', 'цибуля', 'спеції'],
    price: 350,
    weight_grams: 350,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 6,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'shashlyk-mushrooms',
    category_id: 'shashliks',
    name: 'Шашлик з печерицями',
    slug: 'shashlyk-mushrooms',
    description: 'Ароматні печериці з соусом',
    ingredients: ['печериці', 'соус', 'спеції', 'цибуля'],
    price: 150,
    weight_grams: 200,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 7,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'shashlyk-turkey',
    category_id: 'shashliks',
    name: 'Шашлик з індички',
    slug: 'shashlyk-turkey',
    description: 'Ніжний шашлик з філе індички в йогуртовому маринаді',
    ingredients: ['індичка', 'йогурт', 'цибуля', 'спеції'],
    price: 250,
    weight_grams: 300,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 8,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'shashlyk-karsky',
    category_id: 'shashliks',
    name: 'Шашлик по-карськи',
    slug: 'shashlyk-karsky',
    description: 'Великий шашлик з баранини з овочами',
    ingredients: ['баранина', 'помідори', 'перець', 'цибуля'],
    price: 420,
    weight_grams: 400,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 9,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'shashlyk-veal',
    category_id: 'shashliks',
    name: 'Шашлик з телятини',
    slug: 'shashlyk-veal',
    description: "М'який шашлик з молочної телятини",
    ingredients: ['телятина', 'цибуля', 'спеції'],
    price: 340,
    weight_grams: 300,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 10,
    created_at: '',
    updated_at: '',
    categories: catBySlug['shashliks'],
  },
  {
    id: 'steak-ribeye',
    category_id: 'steaks',
    name: 'Стейк Рібай',
    slug: 'steak-ribeye',
    description: 'Преміум стейк з мармурової яловичини',
    ingredients: ['яловичина', 'олія', 'спеції', 'часник'],
    price: 450,
    weight_grams: 350,
    image_url: img('steak-ribeye'),
    is_popular: true,
    is_available: true,
    display_order: 1,
    created_at: '',
    updated_at: '',
    categories: catBySlug['steaks'],
  },
  {
    id: 'steak-filet-mignon',
    category_id: 'steaks',
    name: 'Стейк Філе-міньйон',
    slug: 'steak-filet-mignon',
    description: 'Найтендніший стейк',
    ingredients: ['яловичина', 'вершкове масло', 'спеції'],
    price: 520,
    weight_grams: 300,
    image_url: img('steak-filet-mignon'),
    is_popular: false,
    is_available: true,
    display_order: 2,
    created_at: '',
    updated_at: '',
    categories: catBySlug['steaks'],
  },
  {
    id: 'steak-tbone',
    category_id: 'steaks',
    name: 'Стейк Тібоун',
    slug: 'steak-tbone',
    description: 'Великий стейк на кістці з мармурової яловичини',
    ingredients: ['яловичина на кістці', 'спеції', 'олія'],
    price: 620,
    weight_grams: 500,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 3,
    created_at: '',
    updated_at: '',
    categories: catBySlug['steaks'],
  },
  {
    id: 'steak-striploin',
    category_id: 'steaks',
    name: 'Стейк Стріплойн',
    slug: 'steak-striploin',
    description: 'Пісний стейк ніжної текстури',
    ingredients: ['яловичина', 'спеції', 'розмарин'],
    price: 480,
    weight_grams: 300,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 4,
    created_at: '',
    updated_at: '',
    categories: catBySlug['steaks'],
  },
  {
    id: 'steak-porterhouse',
    category_id: 'steaks',
    name: 'Стейк Портерхаус',
    slug: 'steak-porterhouse',
    description: 'Великий стейк з двох частин: філе та стриплойн',
    ingredients: ['яловичина на кістці', 'спеції', 'олія'],
    price: 750,
    weight_grams: 600,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 5,
    created_at: '',
    updated_at: '',
    categories: catBySlug['steaks'],
  },
  {
    id: 'steak-new-york',
    category_id: 'steaks',
    name: 'Стейк Нью-Йорк',
    slug: 'steak-new-york',
    description: 'Стейк з мармурової яловичини, витриманий сухим способом',
    ingredients: ['яловичина', 'спеції', 'часник'],
    price: 490,
    weight_grams: 320,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 6,
    created_at: '',
    updated_at: '',
    categories: catBySlug['steaks'],
  },
  {
    id: 'steak-salmon',
    category_id: 'steaks',
    name: 'Стейк з лосося',
    slug: 'steak-salmon',
    description: 'Стейк зі свіжого лосося на грилі',
    ingredients: ['лосось', 'лимон', 'спеції', 'кріп'],
    price: 380,
    weight_grams: 250,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 7,
    created_at: '',
    updated_at: '',
    categories: catBySlug['steaks'],
  },
  {
    id: 'pork-rack',
    category_id: 'steaks',
    name: 'Свиняча корейка на кістці',
    slug: 'pork-rack',
    description: 'Соковита свиняча корейка на грилі',
    ingredients: ['свинина на кістці', 'спеції', 'розмарин'],
    price: 350,
    weight_grams: 350,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 8,
    created_at: '',
    updated_at: '',
    categories: catBySlug['steaks'],
  },
  {
    id: 'salad-caesar',
    category_id: 'salads',
    name: 'Салат Цезар',
    slug: 'salad-caesar',
    description: 'Класичний салат з куркою',
    ingredients: ['курка', 'салат айсберг', 'пармезан', 'сухарики', 'соус цезар'],
    price: 180,
    weight_grams: 250,
    image_url: img('salad-caesar'),
    is_popular: true,
    is_available: true,
    display_order: 1,
    created_at: '',
    updated_at: '',
    categories: catBySlug['salads'],
  },
  {
    id: 'salad-greek',
    category_id: 'salads',
    name: 'Грецький салат',
    slug: 'salad-greek',
    description: 'Свіжий салат з овочів',
    ingredients: ['помідори', 'огірки', 'перець', 'цибуля', 'фетакса', 'олії'],
    price: 160,
    weight_grams: 250,
    image_url: img('salad-greek'),
    is_popular: false,
    is_available: true,
    display_order: 2,
    created_at: '',
    updated_at: '',
    categories: catBySlug['salads'],
  },
  {
    id: 'salad-beetroot',
    category_id: 'salads',
    name: 'Салат з печеним буряком',
    slug: 'salad-beetroot',
    description: 'Теплий салат з буряком та козячим сиром',
    ingredients: ['буряк', 'козячий сир', 'руккола', 'горіхи'],
    price: 190,
    weight_grams: 220,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 3,
    created_at: '',
    updated_at: '',
    categories: catBySlug['salads'],
  },
  {
    id: 'salad-meat',
    category_id: 'salads',
    name: "Салат м'ясний",
    slug: 'salad-meat',
    description: 'Ситний салат з яловичиною та овочами',
    ingredients: ['яловичина', 'овочі', 'соус', 'зелень'],
    price: 220,
    weight_grams: 280,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 4,
    created_at: '',
    updated_at: '',
    categories: catBySlug['salads'],
  },
  {
    id: 'salad-tuna',
    category_id: 'salads',
    name: 'Салат з тунцем',
    slug: 'salad-tuna',
    description: 'Салат з тунцем, яйцем та свіжими овочами',
    ingredients: ['тунець', 'яйця', 'помідори', 'салат', 'оливки'],
    price: 210,
    weight_grams: 250,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 5,
    created_at: '',
    updated_at: '',
    categories: catBySlug['salads'],
  },
  {
    id: 'salad-mushroom',
    category_id: 'salads',
    name: 'Салат з печерицями',
    slug: 'salad-mushroom',
    description: 'Теплий салат з печерицями та шпинатом',
    ingredients: ['печериці', 'шпинат', 'пармезан', 'соус'],
    price: 185,
    weight_grams: 240,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 6,
    created_at: '',
    updated_at: '',
    categories: catBySlug['salads'],
  },
  {
    id: 'salad-olivier',
    category_id: 'salads',
    name: "Салат Олів'є",
    slug: 'salad-olivier',
    description: "Класичний салат Олів'є з куркою",
    ingredients: ['курка', 'картопля', 'яйця', 'огірки', 'горошок'],
    price: 150,
    weight_grams: 250,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 7,
    created_at: '',
    updated_at: '',
    categories: catBySlug['salads'],
  },
  {
    id: 'salad-vinaigrette',
    category_id: 'salads',
    name: 'Вінегрет',
    slug: 'salad-vinaigrette',
    description: 'Традиційний вінегрет з овочів',
    ingredients: ['буряк', 'картопля', 'квашена капуста', 'цибуля'],
    price: 120,
    weight_grams: 220,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 8,
    created_at: '',
    updated_at: '',
    categories: catBySlug['salads'],
  },
  {
    id: 'borsch',
    category_id: 'soups',
    name: 'Борщ український',
    slug: 'borsch',
    description: 'Традиційний український борщ',
    ingredients: ['буряк', 'капуста', 'картопля', 'морква', 'цибуля', "м'ясо"],
    price: 95,
    weight_grams: 350,
    image_url: img('borsch'),
    is_popular: true,
    is_available: true,
    display_order: 1,
    created_at: '',
    updated_at: '',
    categories: catBySlug['soups'],
  },
  {
    id: 'solyanka',
    category_id: 'soups',
    name: "Солянка м'ясна",
    slug: 'solyanka',
    description: "Навариста м'ясна солянка",
    ingredients: ['яловичина', 'ковбаса', 'огірки', 'олівки', 'лимон'],
    price: 110,
    weight_grams: 350,
    image_url: img('solyanka'),
    is_popular: false,
    is_available: true,
    display_order: 2,
    created_at: '',
    updated_at: '',
    categories: catBySlug['soups'],
  },
  {
    id: 'chicken-noodle-soup',
    category_id: 'soups',
    name: 'Курячий суп з локшиною',
    slug: 'chicken-noodle-soup',
    description: 'Ніжний курячий суп з домашньою локшиною',
    ingredients: ['курка', 'локшина', 'морква', 'цибуля'],
    price: 85,
    weight_grams: 350,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 3,
    created_at: '',
    updated_at: '',
    categories: catBySlug['soups'],
  },
  {
    id: 'mushroom-cream-soup',
    category_id: 'soups',
    name: 'Грибний крем-суп',
    slug: 'mushroom-cream-soup',
    description: 'Ніжний крем-суп з лісових грибів',
    ingredients: ['гриби', 'вершки', 'картопля', 'цибуля'],
    price: 120,
    weight_grams: 300,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 4,
    created_at: '',
    updated_at: '',
    categories: catBySlug['soups'],
  },
  {
    id: 'fish-soup',
    category_id: 'soups',
    name: 'Юшка рибна',
    slug: 'fish-soup',
    description: 'Навариста рибна юшка зі свіжої риби',
    ingredients: ['риба', 'картопля', 'морква', 'лавровий лист'],
    price: 130,
    weight_grams: 350,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 5,
    created_at: '',
    updated_at: '',
    categories: catBySlug['soups'],
  },
  {
    id: 'cheese-chicken-soup',
    category_id: 'soups',
    name: 'Суп сирний з куркою',
    slug: 'cheese-chicken-soup',
    description: 'Ніжний сирний суп з куркою',
    ingredients: ['курка', 'плавлений сир', 'картопля', 'морква'],
    price: 100,
    weight_grams: 350,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 6,
    created_at: '',
    updated_at: '',
    categories: catBySlug['soups'],
  },
  {
    id: 'pea-soup',
    category_id: 'soups',
    name: 'Суп гороховий',
    slug: 'pea-soup',
    description: "Наваристий гороховий суп з м'ясом",
    ingredients: ['горох', 'свинина', 'картопля', 'цибуля'],
    price: 90,
    weight_grams: 350,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 7,
    created_at: '',
    updated_at: '',
    categories: catBySlug['soups'],
  },
  {
    id: 'okroshka',
    category_id: 'soups',
    name: 'Окрошка',
    slug: 'okroshka',
    description: 'Холодний суп на кефірі',
    ingredients: ['кефір', 'редиска', 'огірки', 'яйця', 'зелень'],
    price: 85,
    weight_grams: 350,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 8,
    created_at: '',
    updated_at: '',
    categories: catBySlug['soups'],
  },
  {
    id: 'potato-village',
    category_id: 'garnirs',
    name: 'Картопля по-селянськи',
    slug: 'potato-village',
    description: 'Смажена картопля з салом',
    ingredients: ['картопля', 'сало', 'цибуля', 'часник'],
    price: 85,
    weight_grams: 200,
    image_url: img('potato-village'),
    is_popular: true,
    is_available: true,
    display_order: 1,
    created_at: '',
    updated_at: '',
    categories: catBySlug['garnirs'],
  },
  {
    id: 'vegetables-grill',
    category_id: 'garnirs',
    name: 'Овочі гриль',
    slug: 'vegetables-grill',
    description: 'Смажені овочі на грилі',
    ingredients: ['перець', 'кабачок', 'баклажан', 'помідори'],
    price: 90,
    weight_grams: 200,
    image_url: img('vegetables-grill'),
    is_popular: false,
    is_available: true,
    display_order: 2,
    created_at: '',
    updated_at: '',
    categories: catBySlug['garnirs'],
  },
  {
    id: 'rice-vegetables',
    category_id: 'garnirs',
    name: 'Рис з овочами',
    slug: 'rice-vegetables',
    description: 'Розсипчастий рис з овочами',
    ingredients: ['рис', 'морква', 'горошок', 'кукурудза'],
    price: 70,
    weight_grams: 200,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 3,
    created_at: '',
    updated_at: '',
    categories: catBySlug['garnirs'],
  },
  {
    id: 'buckwheat-butter',
    category_id: 'garnirs',
    name: 'Гречка з маслом',
    slug: 'buckwheat-butter',
    description: 'Розсипчаста гречка з вершковим маслом',
    ingredients: ['гречка', 'вершкове масло'],
    price: 65,
    weight_grams: 200,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 4,
    created_at: '',
    updated_at: '',
    categories: catBySlug['garnirs'],
  },
  {
    id: 'french-fries',
    category_id: 'garnirs',
    name: 'Картопля фрі',
    slug: 'french-fries',
    description: 'Хрустка картопля фрі з соусом',
    ingredients: ['картопля', 'олія', 'сіль'],
    price: 75,
    weight_grams: 180,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 5,
    created_at: '',
    updated_at: '',
    categories: catBySlug['garnirs'],
  },
  {
    id: 'mashed-potatoes',
    category_id: 'garnirs',
    name: 'Картопляне пюре',
    slug: 'mashed-potatoes',
    description: 'Ніжне картопляне пюре з вершковим маслом',
    ingredients: ['картопля', 'вершкове масло', 'молоко'],
    price: 65,
    weight_grams: 200,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 6,
    created_at: '',
    updated_at: '',
    categories: catBySlug['garnirs'],
  },
  {
    id: 'pasta-sauce',
    category_id: 'garnirs',
    name: 'Паста з соусом',
    slug: 'pasta-sauce',
    description: 'Макарони з домашнім томатним соусом',
    ingredients: ['паста', 'томати', 'базилік', 'пармезан'],
    price: 95,
    weight_grams: 250,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 7,
    created_at: '',
    updated_at: '',
    categories: catBySlug['garnirs'],
  },
  {
    id: 'stewed-beans',
    category_id: 'garnirs',
    name: 'Квасоля тушкована',
    slug: 'stewed-beans',
    description: 'Квасоля з овочами в томатному соусі',
    ingredients: ['квасоля', 'морква', 'томати', 'цибуля'],
    price: 80,
    weight_grams: 200,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 8,
    created_at: '',
    updated_at: '',
    categories: catBySlug['garnirs'],
  },
  {
    id: 'lemonade',
    category_id: 'drinks',
    name: 'Лимонад домашній',
    slug: 'lemonade',
    description: 'Освіжаючий лимонад',
    ingredients: ['лимон', 'м\'ята', 'цукор', 'вода'],
    price: 55,
    weight_grams: 400,
    image_url: img('lemonade'),
    is_popular: true,
    is_available: true,
    display_order: 1,
    created_at: '',
    updated_at: '',
    categories: catBySlug['drinks'],
  },
  {
    id: 'tea-thyme',
    category_id: 'drinks',
    name: 'Чай з чебрецем',
    slug: 'tea-thyme',
    description: 'Ароматний чай з гірського чебрецю',
    ingredients: ['чебрець', 'чай', 'мед'],
    price: 45,
    weight_grams: 300,
    image_url: img('tea-thyme'),
    is_popular: false,
    is_available: true,
    display_order: 2,
    created_at: '',
    updated_at: '',
    categories: catBySlug['drinks'],
  },
  {
    id: 'berry-compote',
    category_id: 'drinks',
    name: 'Компот ягідний',
    slug: 'berry-compote',
    description: 'Домашній компот із сезонних ягід',
    ingredients: ['ягоди', 'цукор', 'вода'],
    price: 40,
    weight_grams: 350,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 3,
    created_at: '',
    updated_at: '',
    categories: catBySlug['drinks'],
  },
  {
    id: 'black-coffee',
    category_id: 'drinks',
    name: 'Кава чорна',
    slug: 'black-coffee',
    description: 'Міцна чорна кава зі свіжомелених зерен',
    ingredients: ['кава', 'цукор за запитом'],
    price: 50,
    weight_grams: 200,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 4,
    created_at: '',
    updated_at: '',
    categories: catBySlug['drinks'],
  },
  {
    id: 'cranberry-juice',
    category_id: 'drinks',
    name: 'Морс журавлинний',
    slug: 'cranberry-juice',
    description: 'Освіжаючий журавлинний морс',
    ingredients: ['журавлина', 'цукор', 'вода'],
    price: 45,
    weight_grams: 350,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 5,
    created_at: '',
    updated_at: '',
    categories: catBySlug['drinks'],
  },
  {
    id: 'apple-juice',
    category_id: 'drinks',
    name: 'Сік яблучний',
    slug: 'apple-juice',
    description: 'Свіжовичавлений яблучний сік',
    ingredients: ['яблука'],
    price: 60,
    weight_grams: 300,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 6,
    created_at: '',
    updated_at: '',
    categories: catBySlug['drinks'],
  },
  {
    id: 'sea-buckthorn-tea',
    category_id: 'drinks',
    name: 'Чай з обліпихи',
    slug: 'sea-buckthorn-tea',
    description: 'Вітамінний чай з обліпихи та імбиру',
    ingredients: ['обліпиха', 'імбир', 'мед'],
    price: 55,
    weight_grams: 300,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 7,
    created_at: '',
    updated_at: '',
    categories: catBySlug['drinks'],
  },
  {
    id: 'homemade-kvas',
    category_id: 'drinks',
    name: 'Квас домашній',
    slug: 'homemade-kvas',
    description: 'Освіжаючий домашній квас',
    ingredients: ['хліб', 'цукор', 'дріжджі'],
    price: 35,
    weight_grams: 400,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 8,
    created_at: '',
    updated_at: '',
    categories: catBySlug['drinks'],
  },
  {
    id: 'uzvar',
    category_id: 'drinks',
    name: 'Узвар',
    slug: 'uzvar',
    description: 'Традиційний український узвар із сухофруктів',
    ingredients: ['сухофрукти', 'мед', 'вода'],
    price: 40,
    weight_grams: 350,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 9,
    created_at: '',
    updated_at: '',
    categories: catBySlug['drinks'],
  },
  {
    id: 'napoleon-cake',
    category_id: 'deserts',
    name: 'Торт Наполеон',
    slug: 'napoleon-cake',
    description: 'Класичний торт з заварним кремом',
    ingredients: ['тісто', 'крем', 'ваніль'],
    price: 85,
    weight_grams: 150,
    image_url: img('napoleon-cake'),
    is_popular: true,
    is_available: true,
    display_order: 1,
    created_at: '',
    updated_at: '',
    categories: catBySlug['deserts'],
  },
  {
    id: 'honey-cake',
    category_id: 'deserts',
    name: 'Медовик',
    slug: 'honey-cake',
    description: 'Ніжний медовий торт',
    ingredients: ['мед', 'тісто', 'сметанний крем'],
    price: 75,
    weight_grams: 150,
    image_url: img('honey-cake'),
    is_popular: false,
    is_available: true,
    display_order: 2,
    created_at: '',
    updated_at: '',
    categories: catBySlug['deserts'],
  },
  {
    id: 'cheesecake',
    category_id: 'deserts',
    name: 'Чізкейк класичний',
    slug: 'cheesecake',
    description: 'Ніжний чізкейк з вершковим сиром',
    ingredients: ['вершковий сир', 'тісто', 'ягоди', 'ваніль'],
    price: 95,
    weight_grams: 150,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 3,
    created_at: '',
    updated_at: '',
    categories: catBySlug['deserts'],
  },
  {
    id: 'panna-cotta',
    category_id: 'deserts',
    name: 'Панна котта',
    slug: 'panna-cotta',
    description: 'Італійський десерт з полуничним соусом',
    ingredients: ['вершки', 'ваніль', 'полуниця'],
    price: 90,
    weight_grams: 180,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 4,
    created_at: '',
    updated_at: '',
    categories: catBySlug['deserts'],
  },
  {
    id: 'ice-cream',
    category_id: 'deserts',
    name: 'Морозиво пломбір',
    slug: 'ice-cream',
    description: 'Морозиво пломбір з топінгами',
    ingredients: ['пломбір', 'шоколад', 'горіхи'],
    price: 65,
    weight_grams: 150,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 5,
    created_at: '',
    updated_at: '',
    categories: catBySlug['deserts'],
  },
  {
    id: 'tiramisu',
    category_id: 'deserts',
    name: 'Тірамісу',
    slug: 'tiramisu',
    description: 'Італійський десерт маскарпоне',
    ingredients: ['маскарпоне', 'кава', 'бісквіті', 'какао'],
    price: 110,
    weight_grams: 150,
    image_url: '',
    is_popular: true,
    is_available: true,
    display_order: 6,
    created_at: '',
    updated_at: '',
    categories: catBySlug['deserts'],
  },
  {
    id: 'apple-strudel',
    category_id: 'deserts',
    name: 'Штрудель яблучний',
    slug: 'apple-strudel',
    description: 'Тонке тісто з яблуками та корицею',
    ingredients: ['яблука', 'тісто', 'кориця', 'цукор'],
    price: 80,
    weight_grams: 180,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 7,
    created_at: '',
    updated_at: '',
    categories: catBySlug['deserts'],
  },
  {
    id: 'syrnyky',
    category_id: 'deserts',
    name: 'Сирники',
    slug: 'syrnyky',
    description: 'Класичні сирники зі сметаною',
    ingredients: ['сир', 'яйця', 'борошно', 'сметана'],
    price: 70,
    weight_grams: 200,
    image_url: '',
    is_popular: false,
    is_available: true,
    display_order: 8,
    created_at: '',
    updated_at: '',
    categories: catBySlug['deserts'],
  },
];

export const fallbackTables: TableType[] = [
  { id: '1', table_number: 1, seats: 2, table_type: 'square', position_x: 50, position_y: 50, width: 70, height: 70, is_active: true, created_at: '', updated_at: '' },
  { id: '2', table_number: 2, seats: 4, table_type: 'square', position_x: 150, position_y: 50, width: 80, height: 80, is_active: true, created_at: '', updated_at: '' },
  { id: '3', table_number: 3, seats: 4, table_type: 'square', position_x: 270, position_y: 50, width: 80, height: 80, is_active: true, created_at: '', updated_at: '' },
  { id: '4', table_number: 4, seats: 6, table_type: 'round', position_x: 150, position_y: 180, width: 100, height: 100, is_active: true, created_at: '', updated_at: '' },
  { id: '5', table_number: 5, seats: 4, table_type: 'square', position_x: 270, position_y: 180, width: 80, height: 80, is_active: true, created_at: '', updated_at: '' },
  { id: '6', table_number: 6, seats: 8, table_type: 'vip', position_x: 400, position_y: 100, width: 120, height: 100, is_active: true, created_at: '', updated_at: '' },
  { id: '7', table_number: 7, seats: 2, table_type: 'bar', position_x: 50, position_y: 180, width: 70, height: 50, is_active: true, created_at: '', updated_at: '' },
  { id: '8', table_number: 8, seats: 2, table_type: 'bar', position_x: 130, position_y: 180, width: 70, height: 50, is_active: true, created_at: '', updated_at: '' },
  { id: '9', table_number: 9, seats: 4, table_type: 'square', position_x: 50, position_y: 280, width: 80, height: 80, is_active: true, created_at: '', updated_at: '' },
  { id: '10', table_number: 10, seats: 6, table_type: 'round', position_x: 180, position_y: 300, width: 100, height: 100, is_active: true, created_at: '', updated_at: '' },
];
